# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.7"
    }
    
  }

  backend "s3" {}
}

provider "aws" {
  region              = "us-west-2"
}
